language: node_js
node_js:
  - "stable"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
cache:
  yarn: true
  directories:
    - node_modules
env:
  - CI=true
script:
  - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $dugu-defeat
  keep_history: true
  local_dir: storybook-static
  on:
    branch: master
